prepare:
  seed: 77
  split: 0.2
  image_size: [32, 32]
  grayscale: False

train:
  seed: 77
  lr: 0.001
  epochs: 2
  batch: 256
  

model:
  model1:
    params:
      epochs: 3
      batch: 128
    model:
      layer:
        - branche:
          - conv_layers:
              filters: 32
              kernel_size: [3, 3]
              activation: "relu"
          - max_pool:
              pool_size: [3, 3]
          - flatten: 0 
          - dense_layers:
              units: 128
              activation: "relu"
          - output_classes: 100
  model2:
    params:
      lr: 0.003
    model:
      layer:
        - branche:
          - conv_layers:
              filters: 64
              kernel_size: [5, 5]
              activation: "relu"
          - max_pool:
              pool_size: [5, 5]
          - flatten: 0  
          - dense_layers:
              units: 256
              activation: "relu"
          - output_classes: 100
  model3:
    model:
      layer:
        - branche:
          - conv_layers:
              filters: 32
              kernel_size: [3, 3]
              activation: "relu"
          - max_pool:
              pool_size: [3, 3] 
          - conv_layers:
              filters: 64
              kernel_size: [3, 3]
              activation: "relu"
          - max_pool:
              pool_size: [3, 3] 
          - flatten: 0
          - dense_layers:
              units: 128
              activation: "relu"
          - output_classes: 100
  model4:
    model:
      MobileNet: 100

