# Configuration File
# ===================================================
# This configuration file defines the setup, parameters, and structure for training
# multiple image classification models. The file is divided 
# into sections for data preparation, training parameters, and model architectures.
# A model can be a custom model or a pre-trained model.
#
# The global parameters can be overridden by the model-specific parameters if needed.
# The model-specific parameters are defined under the model section.
# ===================================================

prepare:
  seed: 77
  split: 0.2
  image_size: [32, 32]
  grayscale: False

train:
  seed: 77
  lr: 0.002
  epochs: 20
  batch: 512
  
model:
  model1:
    params:
      epochs: 15
    model:
      custome:
        - layer:
          - branche:
            - conv_layers:
                filters: 32
                kernel_size: [3, 3]
                activation: "relu"
                padding: "valid"
            - max_pool:
                pool_size: [2, 2] 
            - conv_layers:
                filters: 64
                kernel_size: [3, 3]
                activation: "relu"
                padding: "valid"
            - conv_layers:
                filters: 128
                kernel_size: [3, 3]
                activation: "relu"
                padding: "valid"
            - max_pool:
                pool_size: [2, 2] 
            - flatten: 0
            - dense_layers:
                units: 128
                activation: "relu"
            - output_classes: 100
  model2:
    params:
      epochs: 40
    model:
      custome:
        - layer:
          - branche:
            - conv_layers:
                filters: 32
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - conv_layers:
                filters: 32
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - max_pool:
                pool_size: [2, 2]
            - dropout : 0.25 
            - conv_layers:
                filters: 64
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - conv_layers:
                filters: 64
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - max_pool:
                pool_size: [2, 2]
            - dropout : 0.25
            - conv_layers:
                filters: 128
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - conv_layers:
                filters: 128
                kernel_size: [3, 3]
                activation: "relu"
                padding: "same"
            - batch_norm: 0
            - max_pool:
                pool_size: [2, 2]
            - dropout : 0.4  
            - flatten: 0
            - dense_layers:
                units: 512
                activation: "relu"
            - batch_norm: 0
            - dropout : 0.5 
            - output_classes: 100
  model3:
    params:
      epochs: 10
    model:
      EfficientNetB0: 100

    

